version: '3.8'

services:
  telegraph-finder:
    build: .
    container_name: telegraph-finder
    restart: unless-stopped
    
    ports:
      - "3000:3000"
    
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET:-change-this-secret}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-}
    
    volumes:
      # 持久化数据库
      - ./data:/app/auth.db
      # 持久化上传文件
      - ./uploads:/app/uploads
      # 持久化日志
      - ./logs:/app/logs
    
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: telegraph-finder-nginx
    restart: unless-stopped
    
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    
    depends_on:
      - telegraph-finder
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
